# Kubernetes Deployment and Service for product-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        # Use the Docker image built from the provided Node.js Dockerfile
        image: your-docker-repo/product-service:latest
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_HOST
          value: "product-db"
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_NAME
          value: "products"
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: product-db-secret
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: product-db-secret
              key: password
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: product-service
