apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        # Use the Docker image built from the provided Node.js Dockerfile
        image: your-docker-repo/order-service:latest
        ports:
        - containerPort: 4000
        # Example environment variables for an orders database
        env:
        - name: DATABASE_HOST
          value: "order-db"
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_NAME
          value: "orders"
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: order-db-secret
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: order-db-secret
              key: password
        readinessProbe:
          httpGet:
            path: /healthz
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 4000
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 4000
    protocol: TCP
    name: http
  selector:
    app: order-service
